import { Box, Button, Heading } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { supabase } from '../utils/supabaseClient'
import { useRouter } from 'next/router';
import enforceAuth from '../utils/enforceAuth';
import Header from '../components/Header';

const Home: NextPage = () => {

  const router = useRouter();

  const handleSignOut = async () => {
    try {
      const { error } = await supabase.auth.signOut();
      console.log('Logged out');
      router.push('/login')
    }catch(error) {
      console.log(error);
    } 
  }

  // Logged in
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header signOut={handleSignOut} />
    </Box>
  )
}

export const getServerSideProps = enforceAuth();

export default Home
