import { Box, Flex, Center, Heading, Stack, Input, Button } from '@chakra-ui/react'
import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { supabase } from '../utils/supabaseClient'

const SignUp: NextPage = () => {

    const [loading, setLoading] = useState(false)
    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')
  
    const handleSignUp = async (email: string, password: string) => {
      try {
        console.log(`email : ${email} pw: ${password}`)
        setLoading(true)
        const { user, session, error } = await supabase.auth.signUp({ email, password })
        if (error) throw error
            alert('Signed UP!')
            console.log(user)
        } catch (error: any) {
            alert(error.error_description || error.message)
        } finally {
            setLoading(false)
        }
    }

    return (
        <Box w='100vw' h='100vh' bg='gray.100'>
            <Head>
                <title>Sign Up</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Center w='100%' h='100%'>
                <Flex direction='column' p={8} bg='white' borderRadius='12px' boxShadow='0 2px 12px #285E6120'>
                    <Heading color='teal.800' size='lg' mb={8} textAlign='center'>Sign Up</Heading>
                    <Stack spacing={4} >
                        <Input type='email' placeholder='Email' size='md'onChange={(e) =>   setEmail(e.target.value)}/>
                        <Input type='password' placeholder='Password' size='md' onChange={(e) => setPassword(e.target.value)}/>
                        <Button colorScheme='teal' type='submit' onClick={(e) => { 
                                e.preventDefault()
                                handleSignUp(email, password)
                            }
                        }>
                            {loading ? 'Submitting...' : 'Submit'}
                        </Button>
                    </Stack>
                </Flex>
            </Center>
        </Box>
    )
}

export default SignUp